# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower',
            field=models.ManyToManyField(related_name='Followers', to='GameApp.UserProfile'),
        ),
    ]
