# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_userprofile_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follower',
            field=models.ManyToManyField(related_name='followed_by', to='GameApp.UserProfile'),
        ),
    ]
