# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_auto_20170612_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['user', 'score', 'date']},
        ),
    ]
